version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017" # Mapeia a porta 27017 do container para a porta 27017 do host
    volumes:
      - mongo-data:/data/db # Define um volume nomeado para persistência de dados
    environment:
      MONGO_INITDB_ROOT_USERNAME: adminonemessage
      MONGO_INITDB_ROOT_PASSWORD: onemessage

volumes:
  mongo-data:
    driver: local